# Generated by Django 5.0.2 on 2024-02-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopingHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCompra', models.DateField(auto_now_add=True, db_column='fecha_compra')),
                ('totalGastado', models.FloatField()),
            ],
            options={
                'db_table': 'historial_compras',
            },
        ),
    ]
