# Generated by Django 5.0.2 on 2024-02-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuscriptionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSuscripcion', models.CharField(choices=[('FULL', 'FULL'), ('INTER', 'INTERDIARIO'), ('MAQ', 'SOLO MAQUINAS'), ('DANCE', 'SOLO BAILE')], max_length=40)),
                ('precioTotal', models.FloatField()),
                ('precioPagado', models.FloatField()),
                ('descuento', models.FloatField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('estado', models.CharField(choices=[('ALDIA', 'AL DIA'), ('PENDIENTE', 'PENDIENTE DE PAGO'), ('BLOQUEADO', 'BLOQUEADO')], max_length=40)),
            ],
            options={
                'db_table': 'suscripciones',
            },
        ),
    ]
