# Generated by Django 5.0.2 on 2024-02-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingDetailModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadComprada', models.IntegerField()),
                ('precioUnitario', models.FloatField()),
            ],
            options={
                'db_table': 'detalles_compra',
            },
        ),
    ]
