# Generated by Django 5.0.2 on 2024-02-28 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shopping_detail', '0001_initial'),
        ('shopping_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingdetailmodels',
            name='id_compra',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='historial_compras', to='shopping_history.shopinghistorymodel'),
        ),
        migrations.AddField(
            model_name='shoppingdetailmodels',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='products.productsmodel'),
        ),
    ]
